<a href="https://colab.research.google.com/github/KUNALKEDARI20/Data-science/blob/main/SAssociation_Rules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import libraries

In [1]:
#Here we want to understand which features are strongly associated to survived = yes. eg. if 1st class, Male->Yes OR female->yes
#Install 'mlxtend' Library if not installed already
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.10/dist-packages (0.22.0)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.11.4)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.25.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (2.0.3)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.2.2)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (3.7.1)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.4.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from mlxtend) (67.7.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.53.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24.2->mlxtend) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.0.2->mlxtend) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [2]:
import mlxtend

In [3]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder

In [4]:
titanic = pd.read_csv("Titanic.csv")
titanic

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

     Class  Gender    Age Survived
0      3rd    Male  Child       No
1      3rd    Male  Child       No
2      3rd    Male  Child       No
3      3rd    Male  Child       No
4      3rd    Male  Child       No
...    ...     ...    ...      ...
2196  Crew  Female  Adult      Yes
2197  Crew  Female  Adult      Yes
2198  Crew  Female  Adult      Yes
2199  Crew  Female  Adult      Yes
2200  Crew  Female  Adult      Yes

[2201 rows x 4 columns]

In [5]:
titanic['Class'].value_counts()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Class
Crew    885
3rd     706
1st     325
2nd     285
Name: count, dtype: int64

In [6]:
titanic['Gender'].value_counts()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Gender
Male      1731
Female     470
Name: count, dtype: int64

In [7]:
titanic['Age'].value_counts()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Age
Adult    2092
Child     109
Name: count, dtype: int64

In [8]:
titanic['Survived'].value_counts()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Survived
No     1490
Yes     711
Name: count, dtype: int64

# Pre-Processing
As the data is not in transaction formation
We are using transaction Encoder

In [9]:
df=pd.get_dummies(titanic)
df.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,Class_1st,Class_2nd,Class_3rd,Class_Crew,Gender_Female,Gender_Male,Age_Adult,Age_Child,Survived_No,Survived_Yes
0,False,False,True,False,False,True,False,True,True,False
1,False,False,True,False,False,True,False,True,True,False
2,False,False,True,False,False,True,False,True,True,False
3,False,False,True,False,False,True,False,True,True,False
4,False,False,True,False,False,True,False,True,True,False

# Apriori Algorithm

In [10]:
frequent_itemsets = apriori(df, min_support=0.1, use_colnames=True)#df-dataframe, min_support default=0.5
# min_support is a float between 0 and 1 for minumum support of the itemsets returned.
# The support is computed as the fraction transactions_where_item(s)_occur / total_transactions.
frequent_itemsets # output is frequent itemsets: 1-item itemsets, 2-item itemsets etc. with min support criteria

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

     support                                           itemsets
0   0.147660                                        (Class_1st)
1   0.129487                                        (Class_2nd)
2   0.320763                                        (Class_3rd)
3   0.402090                                       (Class_Crew)
4   0.213539                                    (Gender_Female)
5   0.786461                                      (Gender_Male)
6   0.950477                                        (Age_Adult)
7   0.676965                                      (Survived_No)
8   0.323035                                     (Survived_Yes)
9   0.144934                             (Age_Adult, Class_1st)
10  0.118582                             (Class_2nd, Age_Adult)
11  0.231713                           (Gender_Male, Class_3rd)
12  0.284871                             (Age_Adult, Class_3rd)
13  0.239891                           (Survived_No, Class_3rd)
14  0.391640                          (Class_Crew, Gender_Male)
15  0.402090                            (Class_Crew, Age_Adult)
16  0.305770                          (Survived_No, Class_Crew)
17  0.193094                         (Age_Adult, Gender_Female)
18  0.156293                      (Survived_Yes, Gender_Female)
19  0.757383                           (Gender_Male, Age_Adult)
20  0.619718                         (Survived_No, Gender_Male)
21  0.166742                        (Survived_Yes, Gender_Male)
22  0.653339                           (Survived_No, Age_Adult)
23  0.297138                          (Survived_Yes, Age_Adult)
24  0.209905                (Gender_Male, Age_Adult, Class_3rd)
25  0.191731              (Survived_No, Gender_Male, Class_3rd)
26  0.216265                (Survived_No, Age_Adult, Class_3rd)
27  0.391640               (Class_Crew, Gender_Male, Age_Adult)
28  0.304407             (Survived_No, Class_Crew, Gender_Male)
29  0.305770               (Survived_No, Class_Crew, Age_Adult)
30  0.143571           (Survived_Yes, Age_Adult, Gender_Female)
31  0.603816              (Survived_No, Gender_Male, Age_Adult)
32  0.153567             (Survived_Yes, Gender_Male, Age_Adult)
33  0.175829   (Survived_No, Gender_Male, Age_Adult, Class_3rd)
34  0.304407  (Survived_No, Class_Crew, Gender_Male, Age_Adult)

In [11]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0.7) # min_threshold is Confidence
rules # http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/
rules.sort_values('lift',ascending = False)[0:20]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
66,"(Age_Adult, Gender_Female)",(Survived_Yes),0.193094,0.323035,0.143571,0.743529,2.301699,0.081195,2.639542,0.700873
67,(Survived_Yes),"(Age_Adult, Gender_Female)",0.323035,0.193094,0.143571,0.444444,2.301699,0.081195,1.452431,0.835403
19,(Gender_Female),(Survived_Yes),0.213539,0.323035,0.156293,0.731915,2.265745,0.087312,2.525187,0.710327
18,(Survived_Yes),(Gender_Female),0.323035,0.213539,0.156293,0.483826,2.265745,0.087312,1.523634,0.825219
64,"(Survived_Yes, Age_Adult)",(Gender_Female),0.297138,0.213539,0.143571,0.483180,2.262724,0.080121,1.521732,0.793974
69,(Gender_Female),"(Survived_Yes, Age_Adult)",0.213539,0.297138,0.143571,0.672340,2.262724,0.080121,2.145099,0.709577
96,"(Survived_No, Class_Crew)","(Gender_Male, Age_Adult)",0.305770,0.757383,0.304407,0.995542,1.314450,0.072822,54.427079,0.344592
101,"(Gender_Male, Age_Adult)","(Survived_No, Class_Crew)",0.757383,0.305770,0.304407,0.401920,1.314450,0.072822,1.160764,0.986022
48,"(Gender_Male, Age_Adult)",(Class_Crew),0.757383,0.402090,0.391640,0.517097,1.286022,0.087104,1.238157,0.916706
49,(Class_Crew),"(Gender_Male, Age_Adult)",0.402090,0.757383,0.391640,0.974011,1.286022,0.087104,9.335480,0.371976
104,(Gender_Male),"(Survived_No, Class_Crew, Age_Adult)",0.786461,0.305770,0.304407,0.387060,1.265851,0.063931,1.132622,0.983509
93,"(Survived_No, Class_Crew, Age_Adult)",(Gender_Male),0.305770,0.786461,0.304407,0.995542,1.265851,0.063931,47.903983,0.302519
52,"(Survived_No, Class_Crew)",(Gender_Male),0.305770,0.786461,0.304407,0.995542,1.265851,0.063931,47.903983,0.302519
57,(Gender_Male),"(Survived_No, Class_Crew)",0.786461,0.305770,0.304407,0.387060,1.265851,0.063931,1.132622,0.983509
103,(Class_Crew),"(Survived_No, Gender_Male, Age_Adult)",0.402090,0.603816,0.304407,0.757062,1.253795,0.061619,1.630802,0.338549
94,"(Survived_No, Gender_Male, Age_Adult)",(Class_Crew),0.603816,0.402090,0.304407,0.504138,1.253795,0.061619,1.205800,0.510929
11,(Gender_Male),(Class_Crew),0.786461,0.402090,0.391640,0.497978,1.238474,0.075412,1.191004,0.901730
50,(Gender_Male),"(Class_Crew, Age_Adult)",0.786461,0.402090,0.391640,0.497978,1.238474,0.075412,1.191004,0.901730
47,"(Class_Crew, Age_Adult)",(Gender_Male),0.402090,0.786461,0.391640,0.974011,1.238474,0.075412,8.216621,0.322047
10,(Class_Crew),(Gender_Male),0.402090,0.786461,0.391640,0.974011,1.238474,0.075412,8.216621,0.322047

In [12]:
rules[rules.lift>1]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Age_Adult),(Class_1st),0.950477,0.147660,0.144934,0.152486,1.032680,0.004587,1.005694,0.639010
1,(Class_1st),(Age_Adult),0.147660,0.950477,0.144934,0.981538,1.032680,0.004587,2.682493,0.037128
8,(Survived_No),(Class_3rd),0.676965,0.320763,0.239891,0.354362,1.104747,0.022745,1.052040,0.293515
9,(Class_3rd),(Survived_No),0.320763,0.676965,0.239891,0.747875,1.104747,0.022745,1.281251,0.139592
10,(Class_Crew),(Gender_Male),0.402090,0.786461,0.391640,0.974011,1.238474,0.075412,8.216621,0.322047
...,...,...,...,...,...,...,...,...,...,...
101,"(Gender_Male, Age_Adult)","(Survived_No, Class_Crew)",0.757383,0.305770,0.304407,0.401920,1.314450,0.072822,1.160764,0.986022
102,(Survived_No),"(Class_Crew, Gender_Male, Age_Adult)",0.676965,0.391640,0.304407,0.449664,1.148157,0.039280,1.105434,0.399458
103,(Class_Crew),"(Survived_No, Gender_Male, Age_Adult)",0.402090,0.603816,0.304407,0.757062,1.253795,0.061619,1.630802,0.338549
104,(Gender_Male),"(Survived_No, Class_Crew, Age_Adult)",0.786461,0.305770,0.304407,0.387060,1.265851,0.063931,1.132622,0.983509
105,(Age_Adult),"(Survived_No, Class_Crew, Gender_Male)",0.950477,0.304407,0.304407,0.320268,1.052103,0.015075,1.023334,1.000000

# Another Example with Retail_Dataset

In [13]:
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [14]:
df = pd.read_csv('/content/retail_dataset.csv')
df.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

FileNotFoundError: [Errno 2] No such file or directory: '/content/retail_dataset.csv'

In [ ]:
df.shape

In [ ]:
# Find unique values of column index 0.
items = (df['0'].unique())
items

In [ ]:
# One-hot encoding
encoded_vals = []
for index, row in df.iterrows(): # iterrows() returns index and content for each row
    labels = {}
    uncommons = list(set(items) - set(row))#total 9 items (Bagel,Milk,...,pencil) - items present in row = Bagel, Milk (for 1st row these 2 items are not present)
    commons = list(set(items).intersection(row))# common items
    for uc in uncommons:
        labels[uc] = 0 # assign 0 to uncommon items
    for com in commons:
        labels[com] = 1# assign 1 to common items
    encoded_vals.append(labels)

In [ ]:
encoded_vals

In [ ]:
ohe_df = pd.DataFrame(encoded_vals)

In [ ]:
ohe_df

In [ ]:
freq_items = apriori(ohe_df, min_support = 0.2, use_colnames = True)

In [ ]:
freq_items

In [ ]:
asso_rules=association_rules(freq_items, metric = "confidence", min_threshold = 0.6) # can use metric as lift

In [ ]:
asso_rules

In [ ]:
asso_rules.sort_values('confidence',ascending = False) # can sort as lift value